(() => {
  const $ = (id) => document.getElementById(id);
  const DATA = {
    "Junior Infants": {stage:"Stage 1",skills:["Listening & rhyme","Syllables","Initial sounds","Letter–sound links","Oral blending"],games:["Sound-a-Saurus","Rhyme River","Feed the Fish"],words:["cat","dog","sun","map","pig","hat"],desc:"Playful listening, rhyme, syllables, early phoneme awareness and beginning letter–sound knowledge."},
    "Senior Infants": {stage:"Stage 1",skills:["Phoneme isolation","CVC blending","CVC segmenting","Digraphs","High-frequency words"],games:["Dragon Word Forge","Feed the Fish","Missing Letter"],words:["ship","chat","fish","shop","ring","frog"],desc:"Secure letter–sound knowledge with blending, segmenting, digraphs and early word recognition."},
    "First Class": {stage:"Stage 2",skills:["Blends & digraphs","Long-vowel patterns","Word families","Sentence reading","Spelling"],games:["Word Forge","Word Family Rapids","Animal Rescue"],words:["rain","boat","green","black","train","sleep"],desc:"Develop automatic word recognition, broader phonics patterns, spelling strategies and sentence reading."},
    "Second Class": {stage:"Stage 2",skills:["Complex patterns","Syllables","Suffixes","Fluency","Spelling strategies"],games:["Dragon Spelling","Dinosaur Word Lab","Ocean Word Quest"],words:["jumping","helpful","sunset","teacher","market","playing"],desc:"Consolidate patterns and syllables, extend spelling strategies, vocabulary and fluent reading."}
  };
  const WORLDS={Dinosaurs:["🦖","Dinosaur Valley"],Dragons:["🐉","Dragon Mountain"],Animals:["🐯","Animal Island"],Ocean:["🐠","Ocean Kingdom"],Fruit:["🍓","Fruit Forest"]};
  const DEFAULT_PROFILE={id:"learner-1",name:"Learner 1",age:5,cls:"Junior Infants",gender:"",mode:"Beginner",interest:"Dinosaurs",stars:0,attempts:0,correct:0,schoolWords:[],mastery:{"Sound awareness":72,"Letter sounds":58,"Blending":42,"Spelling":25}};
  let state=load(),currentGame=0,qIndex=0,sessionDone=0,answered=false,helpStep=0;
  function load(){try{const s=JSON.parse(localStorage.getItem("letterquest-ireland-v1"));if(s&&Array.isArray(s.profiles)&&s.profiles.length)return s;}catch(e){}return{profiles:[DEFAULT_PROFILE],currentId:DEFAULT_PROFILE.id};}
  function save(){localStorage.setItem("letterquest-ireland-v1",JSON.stringify(state));}
  function current(){return state.profiles.find(p=>p.id===state.currentId)||state.profiles[0];}
  function clamp(n,a,b){return Math.max(a,Math.min(b,n));}
  function shuffle(a){return [...a].sort(()=>Math.random()-.5);}
  function speak(text){if(!("speechSynthesis" in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.72;u.pitch=1.02;u.lang="en-IE";speechSynthesis.speak(u);}
  function phonemes(word){const out=[],dig=["sh","ch","th","ng","ee","ai","oa","oo","ck"];let i=0;while(i<word.length){const pair=word.slice(i,i+2);if(dig.includes(pair)){out.push("/"+pair+"/");i+=2}else{out.push("/"+word[i]+"/");i++;}}return out;}
  function renderProfiles(){const box=$("profileSelect");box.innerHTML="";state.profiles.forEach(p=>{const o=document.createElement("option");o.value=p.id;o.textContent=`${p.name} · ${p.cls}`;box.appendChild(o);});box.value=state.currentId;}
  function renderGames(){const p=current(),d=DATA[p.cls],box=$("gameList");box.innerHTML="";d.games.forEach((g,i)=>{const b=document.createElement("button");b.className="game-button"+(i===currentGame?" active":"");b.type="button";b.textContent=(["🦖","🐉","🐠"][i%3])+" "+g;b.addEventListener("click",()=>{currentGame=i;qIndex=0;sessionDone=0;renderGames();newQuestion();});box.appendChild(b);});$("difficulty").value=p.mode;$("theme").value=p.interest;}
  function gameName(){const d=DATA[current().cls];return d.games[currentGame%d.games.length];}
  function buildQuestion(){const p=current(),d=DATA[p.cls],advanced=$("difficulty").value==="Advanced",words=p.schoolWords.length?p.schoolWords:d.words,word=(words[qIndex%words.length]||"cat").toLowerCase().replace(/[^a-z]/g,"")||"cat",game=gameName();if(game.includes("Sound")||game.includes("Rhyme")){const answer=word[0],opts=shuffle([...new Set([answer,"m","s","t","p","f"])]).slice(0,4);return{type:"letter",word,answer,opts,question:advanced?`Which letter begins the word “${word}”?`:`Which letter makes the sound /${answer}/?`,say:advanced?word:answer,skill:"Phoneme isolation · letter–sound link"};}if(game.includes("Missing")){const pos=advanced?Math.min(1,word.length-1):0,answer=word[pos],shown=word.split("").map((c,i)=>i===pos?"_":c.toUpperCase()).join(" "),opts=shuffle([...new Set([answer,"a","e","i","o"])]).slice(0,4);return{type:"letter",word,answer,opts,question:`Complete the word: ${shown}`,say:word,skill:"Segmenting · spelling"};}return{type:"build",word,answer:word,opts:shuffle(word.split("")),question:advanced?`Spell “${word}” from memory.`:`Build the word “${word}”.`,say:word,skill:"Blending · segmenting · spelling"};}
  function newQuestion(){answered=false;helpStep=0;$("nextBtn").disabled=true;$("feedback").textContent="";const p=current(),q=buildQuestion(),world=WORLDS[p.interest]||WORLDS.Dinosaurs;$("worldLabel").textContent=world[1];$("mascot").textContent=world[0];$("gameTitle").textContent=gameName();$("question").textContent=q.question;$("skillLabel").textContent=q.skill;$("instruction").textContent=q.type==="build"?"Tap letters in order to build the word.":"Tap the best answer.";$("sessionCount").textContent=`${sessionDone} / 5`;$("sessionBar").style.width=(sessionDone*20)+"%";const area=$("answerArea");area.innerHTML="";if(q.type==="letter"){q.opts.forEach(x=>{const b=document.createElement("button");b.type="button";b.className="answer-btn";b.textContent=x.toUpperCase();b.addEventListener("click",()=>checkLetter(b,x,q));area.appendChild(b);});}else{let built="";const readout=document.createElement("div");readout.className="built";readout.setAttribute("aria-live","polite");area.appendChild(readout);q.opts.forEach(x=>{const b=document.createElement("button");b.type="button";b.className="answer-btn";b.textContent=x.toUpperCase();b.addEventListener("click",()=>{if(answered)return;built+=x;readout.textContent=built.toUpperCase();b.disabled=true;if(built.length===q.answer.length)checkBuild(built,q);});area.appendChild(b);});const reset=document.createElement("button");reset.type="button";reset.className="secondary";reset.textContent="↺ Start again";reset.addEventListener("click",newQuestion);area.appendChild(reset);}}
  function record(ok,skill){const p=current();p.attempts++;if(ok){p.correct++;p.stars++;}let key="Sound awareness";if(skill.toLowerCase().includes("spelling"))key="Spelling";else if(skill.toLowerCase().includes("blending"))key="Blending";else if(skill.toLowerCase().includes("letter"))key="Letter sounds";p.mastery[key]=clamp((p.mastery[key]||45)+(ok?4:-2),10,100);save();$("stars").textContent="⭐ "+p.stars;renderParent();}
  function finish(ok,q){sessionDone=clamp(sessionDone+1,0,5);$("sessionCount").textContent=`${sessionDone} / 5`;$("sessionBar").style.width=(sessionDone*20)+"%";$("feedback").textContent=ok?`⭐ Brilliant! ${q.word.toUpperCase()}.`:`Good try. ${phonemes(q.word).join(" · ")} → ${q.word.toUpperCase()}`;if(!ok)speak(q.word);$("nextBtn").disabled=false;}
  function checkLetter(btn,x,q){if(answered)return;answered=true;const ok=x===q.answer;btn.classList.add(ok?"correct":"wrong");record(ok,q.skill);finish(ok,q);}
  function checkBuild(str,q){if(answered)return;answered=true;const ok=str===q.answer;record(ok,q.skill);finish(ok,q);}
  function renderJourney(){const box=$("journeyGrid");box.innerHTML="";Object.entries(DATA).forEach(([cls,d])=>{const el=document.createElement("article");el.className="journey-card"+(current().cls===cls?" current":"");el.innerHTML=`<strong>${cls}</strong><span class="chip">${d.stage}</span><p class="muted">${d.desc}</p><div class="chips">${d.skills.map(s=>`<span class="chip">${s}</span>`).join("")}</div>`;box.appendChild(el);});}
  function renderSpellings(){const box=$("spellingList");box.innerHTML="";const words=current().schoolWords;if(!words.length){box.innerHTML='<span class="muted">No school words added yet.</span>';return;}words.forEach(w=>{const s=document.createElement("span");s.className="chip";s.textContent=w;box.appendChild(s);});}
  function renderParent(){const p=current();$("parentTitle").textContent=`${p.name} · ${p.cls}`;const box=$("mastery");box.innerHTML="";Object.entries(p.mastery).forEach(([k,v])=>{const row=document.createElement("div");row.className="mastery-row";row.innerHTML=`<div class="mastery-head"><span>${k}</span><span>${Math.round(v)}%</span></div><div class="progress"><span style="width:${clamp(v,0,100)}%"></span></div>`;box.appendChild(row);});const weakest=Object.entries(p.mastery).sort((a,b)=>a[1]-b[1])[0],accuracy=p.attempts?Math.round(100*p.correct/p.attempts):0;$("nextPlan").innerHTML=`<p><strong>Priority:</strong> ${weakest[0]}</p><p>LetterQuest will increase practice here while continuing ${DATA[p.cls].skills.slice(0,3).join(", ").toLowerCase()}.</p><p><strong>Accuracy:</strong> ${accuracy}% across ${p.attempts} attempts.</p>`;renderSpellings();}
  function generateWorksheet(){const p=current(),d=DATA[p.cls],theme=$("sheetTheme").value||p.interest,focus=$("sheetFocus").value,length=$("sheetLength").value,icon=(WORLDS[theme]||WORLDS.Dinosaurs)[0],words=(p.schoolWords.length?p.schoolWords:d.words).slice(0,6),weak=Object.entries(p.mastery).sort((a,b)=>a[1]-b[1])[0][0];$("worksheet").innerHTML=`<header><h2>${icon} LetterQuest Practice</h2><p>${p.name} · ${p.cls} · ${length}</p><p><strong>Focus:</strong> ${focus} &nbsp; <strong>Priority:</strong> ${weak}</p></header><section class="worksheet-section"><h3>1. Say the sounds</h3><p>${words.slice(0,3).map(w=>phonemes(w).join(" &nbsp; ")).join("&nbsp;&nbsp;&nbsp;")}</p></section><section class="worksheet-section"><h3>2. Fill in the missing letters</h3>${words.slice(0,4).map(w=>`<p>${w[0].toUpperCase()} ${Array.from({length:Math.max(1,w.length-1)},()=>"_").join(" ")} &nbsp; ${icon}</p>`).join("")}</section><section class="worksheet-section"><h3>3. Sound boxes</h3>${words.slice(0,3).map(w=>`<p>${w.toUpperCase()} &nbsp; ${phonemes(w).map(()=>'<span class="soundbox"></span>').join("")}</p>`).join("")}</section><section class="worksheet-section"><h3>4. Spelling challenge</h3><p>Write these words without looking:</p><p>${words.join(" &nbsp; · &nbsp; ")}</p><div style="height:70px;border-bottom:1px solid #111"></div></section><section class="worksheet-section"><h3>5. Draw & write</h3><p>Draw something from ${theme} and write one word or sentence about it.</p><div class="drawbox"></div></section>`;}
  $("hearBtn").addEventListener("click",()=>speak(buildQuestion().say));
  $("helpBtn").addEventListener("click",()=>{const q=buildQuestion(),ph=phonemes(q.word);helpStep++;if(helpStep===1){$("feedback").textContent="First sound: "+ph[0];speak(ph[0].replaceAll("/",""));}else if(helpStep===2){$("feedback").textContent=ph.join(" · ");speak(ph.map(x=>x.replaceAll("/","")).join(" "));}else{$("feedback").textContent=ph.join(" → ")+" → "+q.word.toUpperCase();speak(q.word);}});
  $("nextBtn").addEventListener("click",()=>{qIndex++;if(sessionDone>=5)sessionDone=0;newQuestion();});
  $("difficulty").addEventListener("change",()=>{current().mode=$("difficulty").value;save();qIndex=0;newQuestion();});
  $("theme").addEventListener("change",()=>{current().interest=$("theme").value;save();newQuestion();});
  $("profileSelect").addEventListener("change",e=>{state.currentId=e.target.value;save();currentGame=0;qIndex=0;sessionDone=0;renderAll();});
  $("addProfileBtn").addEventListener("click",()=>$("profileDialog").showModal());$("cancelProfileBtn").addEventListener("click",()=>$("profileDialog").close());
  $("profileForm").addEventListener("submit",e=>{e.preventDefault();const name=$("profileName").value.trim(),age=clamp(Number($("profileAge").value)||5,4,9);if(!name)return;const p={id:"p-"+Date.now(),name,age,cls:$("profileClass").value,gender:$("profileGender").value,mode:$("profileMode").value,interest:$("profileInterest").value,stars:0,attempts:0,correct:0,schoolWords:[],mastery:{"Sound awareness":50,"Letter sounds":45,"Blending":35,"Spelling":25}};state.profiles.push(p);state.currentId=p.id;save();$("profileDialog").close();$("profileForm").reset();renderAll();});
  $("spellingForm").addEventListener("submit",e=>{e.preventDefault();current().schoolWords=$("spellingInput").value.split(",").map(x=>x.trim().toLowerCase()).filter(x=>/^[a-z]{2,14}$/.test(x)).slice(0,8);$("spellingInput").value="";save();renderSpellings();newQuestion();});
  document.querySelectorAll(".tab").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b===btn));document.querySelectorAll(".page").forEach(p=>p.classList.add("hidden"));$("page-"+btn.dataset.page).classList.remove("hidden");if(btn.dataset.page==="worksheets")generateWorksheet();}));
  $("generateSheetBtn").addEventListener("click",generateWorksheet);$("printBtn").addEventListener("click",()=>{generateWorksheet();window.print();});
  function renderAll(){const p=current();renderProfiles();renderGames();renderJourney();renderParent();$("stars").textContent="⭐ "+p.stars;$("theme").value=p.interest;newQuestion();}
  renderAll();
})();