(() => {
  const STORE='letterquest-ireland-v1';
  const AVATARS=['🦖','🦄','🐯','🐼','🐠','🍭','🐉','🦊'];
  const THEME={Sweets:{icon:'🍬',world:'Sweet Shop'},Unicorns:{icon:'🦄',world:'Unicorn Meadow'},Dinosaurs:{icon:'🦖',world:'Dinosaur Valley'},Dragons:{icon:'🐉',world:'Dragon Mountain'},Animals:{icon:'🐯',world:'Animal Island'},Ocean:{icon:'🐠',world:'Ocean Kingdom'},Fruit:{icon:'🍓',world:'Fruit Forest'}};
  const $=id=>document.getElementById(id);
  const readState=()=>{try{return JSON.parse(localStorage.getItem(STORE))||{profiles:[]}}catch(e){return{profiles:[]}}};
  const writeState=s=>localStorage.setItem(STORE,JSON.stringify(s));
  const profile=()=>{const s=readState();return s.profiles?.find(p=>p.id===s.currentId)||s.profiles?.[0]};
  function speak(text){if(!text||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-IE';u.rate=.78;u.pitch=1.02;speechSynthesis.speak(u)}
  function addOption(id,value){const s=$(id);if(s&&!Array.from(s.options).some(o=>o.value===value)){const o=document.createElement('option');o.value=o.textContent=value;s.appendChild(o)}}
  ['theme','sheetTheme','profileInterest'].forEach(id=>{addOption(id,'Sweets');addOption(id,'Unicorns')});

  const switcher=document.querySelector('.profile-switch');
  const avatar=document.createElement('div');avatar.className='profile-avatar';avatar.id='profileAvatar';avatar.setAttribute('aria-label','Profile avatar');
  if(switcher)switcher.insertBefore(avatar,$('profileSelect'));
  const edit=document.createElement('button');edit.id='editProfileBtn';edit.type='button';edit.className='secondary';edit.textContent='✏️ Edit profile';if(switcher)switcher.appendChild(edit);

  function renderAvatar(){const p=profile();if(!p||!avatar)return;avatar.innerHTML='';if(p.avatar?.type==='photo'&&p.avatar.src){const img=document.createElement('img');img.src=p.avatar.src;img.alt='';avatar.appendChild(img)}else avatar.textContent=p.avatar?.value||THEME[p.interest]?.icon||'🦖'}
  function themeDecor(){const p=profile();if(!p)return;const t=THEME[p.interest]||THEME[$('theme')?.value];if(!t)return;if($('worldLabel'))$('worldLabel').textContent=t.world;if($('mascot'))$('mascot').textContent=t.icon;const q=$('question');if(q&&['Sweets','Unicorns'].includes(p.interest)){const raw=q.dataset.rawQuestion||q.textContent.replace(/^🍬 Sweet Shop Challenge: |^🦄 Unicorn Meadow Challenge: /,'');q.dataset.rawQuestion=raw;q.textContent=`${t.icon} ${t.world} Challenge: ${raw}`}}
  renderAvatar();setTimeout(themeDecor,50);

  const controls=document.querySelector('.play-zone .controls');
  if(controls&&!$('readQuestionBtn')){const b=document.createElement('button');b.id='readQuestionBtn';b.type='button';b.className='secondary';b.textContent='🗣️ Read question';controls.insertBefore(b,controls.firstChild);b.addEventListener('click',()=>speak($('question')?.dataset.rawQuestion||$('question')?.textContent))}

  const dlg=document.createElement('dialog');dlg.id='editProfileDialog';dlg.innerHTML=`<form id="editProfileForm" method="dialog" class="dialog-form"><h2>Edit child profile</h2><div class="edit-profile-row"><div id="editAvatarPreview" class="profile-avatar" style="width:76px;height:76px;font-size:48px"></div><div><strong>Choose a stock avatar</strong><div id="avatarChoices" class="avatar-grid"></div><label class="field">Or upload a photo from this device<input id="avatarUpload" type="file" accept="image/*"></label><img id="photoPreview" class="photo-preview" alt="Photo preview"></div></div><label class="field">Nickname or initials<input id="editName" maxlength="18" required></label><label class="field">Age<input id="editAge" type="number" min="4" max="9" required></label><label class="field">Class<select id="editClass"><option>Junior Infants</option><option>Senior Infants</option><option>First Class</option><option>Second Class</option></select></label><label class="field">Gender (optional)<select id="editGender"><option value="">Prefer not to say</option><option>Girl</option><option>Boy</option><option>Other</option></select></label><label class="field">Challenge<select id="editMode"><option>Beginner</option><option>Advanced</option></select></label><label class="field">Favourite world<select id="editInterest"><option>Dinosaurs</option><option>Dragons</option><option>Animals</option><option>Ocean</option><option>Fruit</option><option>Sweets</option><option>Unicorns</option></select></label><div class="dialog-actions"><button type="button" id="cancelEditProfile" class="secondary">Cancel</button><button type="submit">Save changes</button></div></form>`;document.body.appendChild(dlg);
  let pendingAvatar=null;
  function drawChoices(){const box=$('avatarChoices');if(!box)return;box.innerHTML='';AVATARS.forEach(v=>{const b=document.createElement('button');b.type='button';b.className='avatar-choice';b.textContent=v;b.addEventListener('click',()=>{pendingAvatar={type:'stock',value:v};document.querySelectorAll('.avatar-choice').forEach(x=>x.classList.toggle('selected',x===b));$('editAvatarPreview').innerHTML=v;$('photoPreview').style.display='none'});box.appendChild(b)})}
  drawChoices();
  function openEdit(){const p=profile();if(!p)return;pendingAvatar=p.avatar||{type:'stock',value:THEME[p.interest]?.icon||'🦖'};$('editName').value=p.name||'';$('editAge').value=p.age||5;$('editClass').value=p.cls;$('editGender').value=p.gender||'';$('editMode').value=p.mode||'Beginner';$('editInterest').value=p.interest||'Dinosaurs';$('editAvatarPreview').innerHTML='';if(pendingAvatar.type==='photo'&&pendingAvatar.src){const im=document.createElement('img');im.src=pendingAvatar.src;im.alt='';$('editAvatarPreview').appendChild(im)}else $('editAvatarPreview').textContent=pendingAvatar.value||'🦖';dlg.showModal()}
  edit.addEventListener('click',openEdit);$('cancelEditProfile').addEventListener('click',()=>dlg.close());
  $('avatarUpload').addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const c=document.createElement('canvas');c.width=c.height=180;const ctx=c.getContext('2d');const scale=Math.max(180/im.width,180/im.height),w=im.width*scale,h=im.height*scale;ctx.drawImage(im,(180-w)/2,(180-h)/2,w,h);const src=c.toDataURL('image/jpeg',.78);pendingAvatar={type:'photo',src};$('photoPreview').src=src;$('photoPreview').style.display='block';$('editAvatarPreview').innerHTML=`<img src="${src}" alt="">`};im.src=r.result};r.readAsDataURL(f)});
  $('editProfileForm').addEventListener('submit',e=>{e.preventDefault();const s=readState(),p=s.profiles.find(x=>x.id===s.currentId)||s.profiles[0];if(!p)return;p.name=$('editName').value.trim()||p.name;p.age=Math.max(4,Math.min(9,Number($('editAge').value)||5));p.cls=$('editClass').value;p.gender=$('editGender').value;p.mode=$('editMode').value;p.interest=$('editInterest').value;p.avatar=pendingAvatar;writeState(s);dlg.close();location.reload()});

  function fireworks(){const layer=document.createElement('div');layer.className='celebration-layer';const symbols=['✨','🎆','🎇','⭐','🌟','💥'];for(let i=0;i<30;i++){const s=document.createElement('span');s.className='spark';s.textContent=symbols[i%symbols.length];const a=Math.random()*Math.PI*2,d=100+Math.random()*260;s.style.setProperty('--x',`${Math.cos(a)*d}px`);s.style.setProperty('--y',`${Math.sin(a)*d}px`);s.style.left=(45+Math.random()*10)+'%';s.style.top=(40+Math.random()*12)+'%';layer.appendChild(s)}document.body.appendChild(layer);setTimeout(()=>layer.remove(),1400)}
  function sad(){const el=document.createElement('div');el.className='sad-pop';el.textContent='😢';document.body.appendChild(el);setTimeout(()=>el.remove(),1200)}
  function quotedWord(text){const m=text.match(/[“\"]([^”\"]+)[”\"]/);return m?.[1]?.toLowerCase()}
  function answerExplanation(ok,selected){const q=($('question')?.dataset.rawQuestion||$('question')?.textContent||'').replace(/^🍬 Sweet Shop Challenge: |^🦄 Unicorn Meadow Challenge: /,'');const fb=$('feedback')?.textContent||'';const word=quotedWord(q)||(fb.match(/→\s*([A-Z]+)\.?$/)?.[1]||'').toLowerCase();let why='';if(/begins/.test(q)&&word){why=`The word ${word} begins with ${word[0]}. The first sound and first letter tell us the answer is ${word[0]}.`}else if(/ends/.test(q)&&word){why=`The word ${word} ends with ${word[word.length-1]}. Listening to the final sound helps us choose that letter.`}else if(/rhymes/.test(q)){why=`Rhyming words have the same ending sound. Say the words slowly and listen to the part at the end.`}else if(/syllables/.test(q)){why=`A syllable is a beat in a word. Say the word slowly and clap once for each beat.`}else if(/Complete the word/.test(q)){why=`We can stretch the word into its sounds and listen for the missing sound, then choose the letter that represents it.`}else if(/sound pattern/.test(q)){why=`The correct choice is the letter pattern you can actually see inside the word. That pattern represents a sound in the word.`}else if(/Add/.test(q)){why=`A suffix is added to the end of a base word. Reading the base word and suffix together makes the new word.`}else if(/Join/.test(q)){why=`A compound word is made by joining two smaller words. Read both parts, then blend them into one word.`}else if(/Listen/.test(q)){why=`This is a quick word-recognition question. The correct answer is the printed word that matches the word you heard.`}else if(word){why=`The correct spelling is ${word}. We can check it by saying the sounds in order and matching each sound or pattern to the letters.`}else why=`The learning clue is in the sounds, letters or word pattern. Try saying the choices aloud and compare them carefully.`;const prefix=ok?'Correct! ':`Not quite. ${selected?`You chose ${selected}. `:''}`;return prefix+why}
  function showFeedback(ok,selected){const f=$('feedback');if(!f)return;const explanation=answerExplanation(ok,selected);f.innerHTML=`<div class="feedback-card ${ok?'good':'try'}"><span class="face">${ok?'🎉':'😢'}</span><div><strong>${ok?'Well done!':'Good try!'}</strong><br>${explanation}<br><button type="button" class="secondary replay-explanation">🔊 Hear explanation again</button></div></div>`;f.querySelector('.replay-explanation')?.addEventListener('click',()=>speak(explanation));ok?fireworks():sad();setTimeout(()=>speak(explanation),450)}
  document.addEventListener('click',e=>{const b=e.target.closest('#answerArea button');if(!b)return;setTimeout(()=>{const f=$('feedback');if(!f)return;const txt=f.textContent||'';if(!txt)return;const ok=b.classList.contains('correct')||txt.includes('Brilliant');const wrong=b.classList.contains('wrong')||txt.includes('Good try');if(ok||wrong)showFeedback(ok,b.textContent.trim())},80)},true);
  const feedbackObserver=$('feedback')?new MutationObserver(()=>{}):null;feedbackObserver?.observe($('feedback'),{childList:true,subtree:true});
  const qObserver=$('question')?new MutationObserver(()=>{if(!$('question').dataset.decorating){$('question').dataset.decorating='1';themeDecor();setTimeout(()=>delete $('question').dataset.decorating,0)}}):null;qObserver?.observe($('question'),{childList:true,subtree:true,characterData:true});
  $('theme')?.addEventListener('change',()=>setTimeout(()=>{renderAvatar();themeDecor()},30));$('profileSelect')?.addEventListener('change',()=>setTimeout(()=>{renderAvatar();themeDecor()},30));
})();